/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgiaovan.ShipperGUI;

import appgiaovan.DTO.AccountDTO;

/**
 *
 * @author HP
 */
public class ShipperMainGUI extends javax.swing.JFrame {

    private final int DonHangDaNhan = 5;
    private final int DonHangDaGiao = 5;
    private final int DonHangGiaoThatBai = 0;
    private AccountDTO accountDTO;
    /**
     * Creates new form ShipperMainScreen
     * @param account
     */
    public ShipperMainGUI(AccountDTO account) {
        initComponents();
        this.accountDTO = account;
        
        jDonHangDaNhan.setText("Đơn hàng đã nhận: " + DonHangDaNhan);
        jDonHangDaGiao.setText("Đơn hàng đã giao: " + DonHangDaGiao);
        jDonHangGiaoThatBai.setText("Đơn hàng giao thất bại: " + DonHangGiaoThatBai);
    }
    public ShipperMainGUI() {
        initComponents();
        this.accountDTO = null;
        jDonHangDaNhan.setText("Đơn hàng đã nhận: " + DonHangDaNhan);
        jDonHangDaGiao.setText("Đơn hàng đã giao: " + DonHangDaGiao);
        jDonHangGiaoThatBai.setText("Đơn hàng giao thất bại: " + DonHangGiaoThatBai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jDonHang = new javax.swing.JButton();
        jBaoCao = new javax.swing.JButton();
        jTroGiup = new javax.swing.JButton();
        jTrangChu = new javax.swing.JButton();
        jCaNhan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDonHangDaNhan = new javax.swing.JLabel();
        jDonHangDaGiao = new javax.swing.JLabel();
        jDonHangGiaoThatBai = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 51));
        jTabbedPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane3.setName("ABC"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("abc");
        setBackground(new java.awt.Color(255, 102, 0));

        jDonHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDonHang.setText("Đơn hàng");
        jDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDonHangActionPerformed(evt);
            }
        });

        jBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBaoCao.setText("Báo cáo");
        jBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaoCaoActionPerformed(evt);
            }
        });

        jTroGiup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTroGiup.setText("Trợ giúp");
        jTroGiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTroGiupActionPerformed(evt);
            }
        });

        jTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTrangChu.setText("Trang chủ");
        jTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrangChuActionPerformed(evt);
            }
        });

        jCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCaNhan.setText("Cá nhân");
        jCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaNhanActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PMIT EXPRESS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SHIPPER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jInternalFrame1.setVisible(true);

        jDonHangDaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDonHangDaNhan.setText("Đơn hàng đã nhận: ");

        jDonHangDaGiao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDonHangDaGiao.setText("Đơn hàng đã giao:");

        jDonHangGiaoThatBai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDonHangGiaoThatBai.setText("Đơn hàng giao thất bại:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDonHangGiaoThatBai)
                    .addComponent(jDonHangDaGiao)
                    .addComponent(jDonHangDaNhan))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jDonHangDaNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDonHangDaGiao)
                .addGap(18, 18, 18)
                .addComponent(jDonHangGiaoThatBai)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDonHangDaNhan.getAccessibleContext().setAccessibleName("jlabelnhan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCaNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTroGiup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTrangChu)
                        .addGap(25, 25, 25)
                        .addComponent(jDonHang)
                        .addGap(24, 24, 24)
                        .addComponent(jBaoCao)
                        .addGap(30, 30, 30)
                        .addComponent(jTroGiup)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(jCaNhan)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDonHangActionPerformed
        // TODO add your handling code here:
        new ShipperProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jDonHangActionPerformed

    private void jBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaoCaoActionPerformed
        // TODO add your handling code here:
        new ShipperReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBaoCaoActionPerformed

    private void jTroGiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTroGiupActionPerformed
        // TODO add your handling code here:
        new ShipperHelp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jTroGiupActionPerformed

    private void jTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrangChuActionPerformed

    private void jCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaNhanActionPerformed
        // TODO add your handling code here:
        new ShipperProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCaNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShipperMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShipperMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShipperMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShipperMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShipperMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaoCao;
    private javax.swing.JButton jCaNhan;
    private javax.swing.JButton jDonHang;
    private javax.swing.JLabel jDonHangDaGiao;
    private javax.swing.JLabel jDonHangDaNhan;
    private javax.swing.JLabel jDonHangGiaoThatBai;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton jTrangChu;
    private javax.swing.JButton jTroGiup;
    // End of variables declaration//GEN-END:variables
}